# Generated by Django 5.1.1 on 2024-10-06 09:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya')),
                ('birth_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2010)], verbose_name="Tug'ilgan yili")),
                ('experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Ish tajribasi')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': "O'qituvchilar",
                'db_table': 'teacher_profile',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.Sh')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon raqam')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'Oddiy foydalanuvchi'), ('teacher', "O'qituvchi"), ('parent', 'Ota-Ona')], default='user', max_length=100, null=True, verbose_name='Foydalanuvchi roli')),
                ('joined_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 6, 14, 39, 50, 680252), null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Farzand ismi')),
                ('child_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Farzand familiyasi')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.group', verbose_name='Guruhi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.users', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Ota-Onalar',
                'db_table': 'parent_profile',
            },
        ),
        migrations.CreateModel(
            name='DailyMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayfiyat', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kayfiyati')),
                ('tartib', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tartibi')),
                ('faollik', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dars davomida faolligi')),
                ('vaqtida_kelish', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Darsga o'z vaqtida kelishi")),
                ('dars_qoldirmaslik', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dars qoldirmasligi')),
                ('vazifa_bajarilganligi', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Uyga vazifasining bajarilganligi')),
                ('darsni_ozlashtirish', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Darsni o'zlashtirishi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 6, 14, 39, 50, 681256), null=True, verbose_name='Time')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.parentprofile', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Daily Mark',
                'verbose_name_plural': 'Kunlik baholar',
                'db_table': 'daily_mark',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teacherprofile', verbose_name="O'qituvchi"),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.users', verbose_name='Foydalanuvchi'),
        ),
    ]
