# Generated by Django 5.1.1 on 2024-10-08 10:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 8, 15, 52, 35, 921545), null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.users', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 8, 15, 52, 35, 919540), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
