# Generated by Django 5.1.3 on 2024-11-09 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_dailymark_created_at_alter_parentprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 9, 6, 58, 38, 635067), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
