# Generated by Django 5.1.1 on 2024-10-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_group_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='child_first_name',
            field=models.CharField(max_length=100, verbose_name='Farzand ismi'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='child_last_name',
            field=models.CharField(max_length=100, verbose_name='Farzand familiyasi'),
        ),
    ]
