# Generated by Django 5.1.1 on 2024-10-05 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_dailymark_description_alter_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymark',
            name='kategory1',
        ),
        migrations.RemoveField(
            model_name='dailymark',
            name='kategory2',
        ),
        migrations.RemoveField(
            model_name='dailymark',
            name='kategory3',
        ),
        migrations.RemoveField(
            model_name='dailymark',
            name='kategory4',
        ),
        migrations.RemoveField(
            model_name='dailymark',
            name='kategory5',
        ),
        migrations.RemoveField(
            model_name='dailymark',
            name='kategory6',
        ),
        migrations.AddField(
            model_name='dailymark',
            name='dars_qoldirmaslik',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dars qoldirmasligi'),
        ),
        migrations.AddField(
            model_name='dailymark',
            name='darsni_ozlashtirish',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Darsni o'zlashtirishi"),
        ),
        migrations.AddField(
            model_name='dailymark',
            name='faollik',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dars davomida faolligi'),
        ),
        migrations.AddField(
            model_name='dailymark',
            name='kayfiyat',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kayfiyati'),
        ),
        migrations.AddField(
            model_name='dailymark',
            name='tartib',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tartibi'),
        ),
        migrations.AddField(
            model_name='dailymark',
            name='vaqtida_kelish',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Darsga o'z vaqtida kelishi"),
        ),
        migrations.AddField(
            model_name='dailymark',
            name='vazifa_bajarilganligi',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Uyga vazifasining bajarilganligi'),
        ),
    ]
