# Generated by Django 5.1.1 on 2024-10-06 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_dailymark_kategory1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 6, 11, 53, 50, 168625), null=True, verbose_name='Time'),
        ),
    ]
